# -*- coding: utf-8 -*-
"""
HEXALIS — site content.
Everything the website says lives here. Edit this file, run `python3 build.py`,
and the HTML is regenerated. No CMS, no framework, no build tooling required.
"""

SITE = {
    "name": "HEXALIS",
    "domain": "hexalis.in",
    "url": "https://hexalis.in",
    "tagline": "Empowering Business. Enabling Possibilities.",
    "promise": "One partner. Every side of your business.",
    "email": "ContactUs@hexalis.in",
    "careers_email": "careers@hexalis.in",
    "instagram": "https://www.instagram.com/hexalis.in",
    "threads": "https://www.threads.com/@hexalis.in",
    # WhatsApp: full international number, digits only (91 = India), as wa.me
    # expects. The message is pre-filled in the chat; the visitor just presses send.
    "whatsapp": "919690573335",
    "whatsapp_display": "+91 96905 73335",
    "whatsapp_message": "Hi HEXALIS, I found you through hexalis.in and would like to start a conversation about how you could help my business.",
    "linkedin": "",
    "description": (
        "HEXALIS is a six-pillar enterprise. Technology, strategy, brand growth, "
        "engagement, workplace and commerce — delivered by one accountable team "
        "instead of six unconnected vendors."
    ),
}

# --------------------------------------------------------------------------
# Icons — hand-drawn line marks, 48x48 grid, stroke uses currentColor.
# --------------------------------------------------------------------------
ICONS = {
    "chip": """<rect x="16" y="16" width="16" height="16" rx="2"/><rect x="21.5" y="21.5" width="5" height="5" rx="1"/>
<path d="M20 16v-5M28 16v-5M20 37v-5M28 37v-5M16 20h-5M16 28h-5M37 20h-5M37 28h-5"/>""",
    "compass": """<circle cx="24" cy="24" r="13"/><path d="M24 11.5v-3M24 39.5v-3M11.5 24h-3M39.5 24h3"/>
<path d="M24 15l2.6 6.4L33 24l-6.4 2.6L24 33l-2.6-6.4L15 24l6.4-2.6z"/>""",
    "growth": """<path d="M12 36V26M20 36V21M28 36V29"/><path d="M11 40h26"/>
<path d="M14 20l8-7 6 5 10-9"/><path d="M31 9h7v7"/>""",
    "triad": """<circle cx="24" cy="13" r="5"/><circle cx="13" cy="32" r="5"/><circle cx="35" cy="32" r="5"/>
<path d="M18.5 17.5 15 25.5M29.5 17.5 33 25.5M18.5 33.5h11"/>""",
    "building": """<path d="M13 39V15l11-6 11 6v24"/><path d="M9 39h30"/>
<path d="M19 21h4M25 21h4M19 27h4M25 27h4M19 33h10"/>""",
    "cart": """<path d="M9 12h4l4.5 17h16L37 17H15"/><circle cx="20" cy="36" r="2.5"/><circle cx="32" cy="36" r="2.5"/>
<path d="M26 6l5 3v5l-5 3-5-3V9z"/>""",
}

# --------------------------------------------------------------------------
# The six pillars — sourced directly from the HEXALIS strategy document.
# --------------------------------------------------------------------------
PILLARS = [
    {
        "num": "01",
        "slug": "technology",
        "name": "Technology",
        "kicker": "Technology, Data, AI & Talent Solutions",
        "tagline": "Connecting Intelligence with Human Potential",
        "outcome": "Potential",
        "icon": "chip",
        "purpose": "Enable businesses to transform, automate and scale through technology, data, AI and specialist talent.",
        "core": "Help organizations use technology, data, AI and specialist talent to improve efficiency, intelligence and business performance.",
        "vision": "To make intelligent technology a catalyst for human and business potential.",
        "mission": "To help organizations harness technology, data, AI and skilled talent to simplify operations, improve decisions and accelerate transformation.",
        "goals": [
            "Build strong capabilities across technology, data, AI and automation.",
            "Develop consulting, implementation and staff augmentation revenue streams.",
            "Create recurring technology engagements and long-term enterprise relationships.",
        ],
        "streams": [
            ("Technology Consulting", "Strategy, architecture, ITSM, governance, transformation"),
            ("Data & AI Solutions", "Analytics, BI, data engineering, AI and GenAI"),
            ("Automation & Implementation", "Workflow, process automation, integrations"),
            ("Talent & Staff Augmentation", "Developers, data engineers, analysts, AI specialists, PMs"),
            ("Managed Services & Support", "Ongoing technology and support services"),
        ],
        "ladder_title": "How the work compounds",
        "ladder": ["Consult", "Implement", "Augment", "Manage"],
        "ladder_note": "Clients rarely need all four on day one. They start where the pain is, and the relationship deepens as trust does — which is why augmentation and managed services become the steady heartbeat of this pillar.",
        "pull": "Technology is only useful when someone stays to run it.",
    },
    {
        "num": "02",
        "slug": "strategy",
        "name": "Strategy",
        "kicker": "Business Strategy, Consulting & Transformation",
        "tagline": "Transforming Vision into Sustainable Value",
        "outcome": "Value",
        "icon": "compass",
        "purpose": "Help businesses define the right direction, improve performance and successfully translate strategy into execution.",
        "core": "Help organizations make better strategic decisions, transform operations and build capabilities for sustainable growth.",
        "vision": "To help ambitious organizations turn bold ideas into enduring business value.",
        "mission": "To combine insight, experience and structured execution to help leaders make better decisions, transform organizations and achieve sustainable outcomes.",
        "goals": [
            "Build capabilities in corporate strategy, management consulting and transformation advisory.",
            "Become a trusted advisory partner to founders, CXOs and business leaders.",
            "Connect strategy with execution rather than limiting HEXALIS to recommendation-only consulting.",
        ],
        "streams": [
            ("Corporate Strategy", "Growth, diversification, market entry, business planning"),
            ("Management Consulting", "Operating model, organization, governance"),
            ("Business Transformation", "Transformation roadmap and execution"),
            ("Operational Excellence", "Process improvement, KPI frameworks"),
            ("PMO & Program Advisory", "PMO setup, governance, portfolio management"),
            ("Executive Advisory", "Ongoing founder and management advisory"),
            ("Learning & Capability", "Corporate workshops, training, masterclasses"),
            ("Professional Talent", "Project managers, business analysts, change and process professionals"),
        ],
        "ladder_title": "Where most consulting stops",
        "ladder": ["Diagnose", "Decide", "Execute", "Embed"],
        "ladder_note": "A recommendation is not an outcome. HEXALIS is built to stay past the deck — into the program, the operating model and the people who have to live with it.",
        "pull": "We do not hand over a slide and wish you luck.",
    },
    {
        "num": "03",
        "slug": "growth",
        "name": "Growth",
        "kicker": "Brand, Marketing & Digital Growth",
        "tagline": "Accelerating Brands towards Greater Possibilities",
        "outcome": "Growth",
        "icon": "growth",
        "purpose": "Build stronger brands, create meaningful market visibility and convert engagement into measurable growth.",
        "core": "Help organizations strengthen their brands, reach the right audiences and convert visibility into measurable business growth.",
        "vision": "To help brands realize their potential and become more relevant, visible and valuable.",
        "mission": "To combine strategy, creativity, content, digital platforms and partnerships to build brands, engage audiences and accelerate measurable growth.",
        "goals": [
            "Establish HEXALIS Growth as the first major market-facing business.",
            "Build capabilities across brand promotion, digital campaigns, creators, content and brand strategy.",
            "Develop a healthy combination of campaign revenue and recurring retainers.",
            "Build strong relationships with marketing leaders in selected high-potential industries.",
        ],
        "streams": [
            ("Brand Strategy", "Positioning, messaging, identity, brand architecture"),
            ("Campaign Management", "Product and brand campaigns"),
            ("Social Media Management", "Content, publishing, community"),
            ("Influencer Marketing", "Creator campaigns and product promotion"),
            ("Content & Creative", "Video, design, copy, corporate content"),
            ("Performance Marketing", "Paid media, acquisition campaigns"),
            ("Lead Generation", "B2B demand generation"),
            ("Digital Presence", "Website, SEO, landing pages"),
        ],
        "ladder_title": "The four offers we lead with",
        "ladder": ["Brand & Product Promotion", "Creator Campaigns", "Digital & Social", "Creative & Content"],
        "ladder_note": "Growth is the first HEXALIS revenue engine and the front door for most relationships. It is deliberately concentrated: four offers done properly beat twenty done thinly.",
        "pull": "Visibility is a means. Revenue is the point.",
    },
    {
        "num": "04",
        "slug": "engagement",
        "name": "Engagement",
        "kicker": "Events & Experiences",
        "tagline": "Inspiring Connections through Memorable Experiences",
        "outcome": "Connection",
        "icon": "triad",
        "purpose": "Create memorable experiences that strengthen connections between organizations, brands and people.",
        "core": "Create meaningful experiences that connect organizations with customers, employees, partners and stakeholders.",
        "vision": "To create experiences that bring people, brands and organizations closer together.",
        "mission": "To design and deliver purposeful experiences, events and activations that inspire participation, strengthen relationships and create lasting memories.",
        "goals": [
            "Build capabilities across corporate events, brand activations, launches and employee and customer engagement.",
            "Develop a dependable national ecosystem of venues, production houses, artists, vendors and specialists.",
            "Cross-sell engagement into existing Growth and corporate accounts.",
        ],
        "streams": [
            ("Corporate Events", "Annual meets, town halls, celebrations"),
            ("Conferences & Summits", "Corporate and industry conferences"),
            ("Product Launches", "Launch events"),
            ("Brand Activations", "Consumer and retail activations"),
            ("Employee Engagement", "Employee programs and events"),
            ("Exhibitions", "Booth design and management"),
            ("Event Production", "AV, staging, creative, content"),
            ("Sponsorship Management", "Sponsor sourcing and management"),
        ],
        "ladder_title": "Deliberately asset-light",
        "ladder": ["Client", "Concept", "Project", "Quality"],
        "ladder_note": "HEXALIS owns the client, the concept, the project and the quality bar. Specialist partners bring the trucks, the trusses and the crew. That keeps the model flexible without diluting who is accountable when the doors open.",
        "pull": "Positioned around experiences, not simply event management.",
    },
    {
        "num": "05",
        "slug": "workplace",
        "name": "Workplace",
        "kicker": "Corporate & Workplace Solutions",
        "tagline": "Strengthening Connections through Purposeful Solutions",
        "outcome": "Purpose",
        "icon": "building",
        "purpose": "Enable organizations to create better employee and workplace experiences through reliable, customized corporate products and solutions.",
        "core": "Help organizations equip, engage and support their people and workplaces through practical corporate solutions.",
        "vision": "To make everyday business interactions more meaningful through thoughtfully designed workplace solutions.",
        "mission": "To provide reliable, customized and purposeful gifting, merchandise, recognition, procurement and workplace solutions that strengthen relationships between organizations, employees and customers.",
        "goals": [
            "Build a curated ecosystem for corporate gifting, merchandise, employee kits, rewards, office supplies and procurement.",
            "Develop reliable supplier relationships with strong quality, pricing and fulfilment standards.",
            "Build recurring B2B procurement and employee-engagement programs rather than depending only on seasonal gifting.",
            "Develop customization and white-label capabilities.",
        ],
        "streams": [
            ("Corporate Gifting", "Festivals, milestones, client gifts"),
            ("Branded Merchandise", "Apparel, bags, bottles, accessories"),
            ("Employee Kits", "Joining, welcome and recognition kits"),
            ("Rewards & Recognition", "Awards and employee rewards"),
            ("Event Merchandise", "Delegate kits and event merchandise"),
            ("Office Supplies", "Regular workplace consumables"),
            ("Corporate Procurement", "Managed sourcing"),
            ("Customized Products", "Client-specific branded products"),
        ],
        "ladder_title": "Built for frequency, not seasons",
        "ladder": ["Source", "Customize", "Fulfil", "Repeat"],
        "ladder_note": "Gifting season is a spike. Onboarding kits, recognition programs and managed procurement are a rhythm. This pillar is designed for the rhythm — high transaction frequency, dependable quality, no last-minute scrambling in October.",
        "pull": "The kit on a new joiner's desk is a brand moment too.",
    },
    {
        "num": "06",
        "slug": "commerce",
        "name": "Commerce",
        "kicker": "Commerce & Digital Products",
        "tagline": "Connecting People with Meaningful Products and Services",
        "outcome": "Scale",
        "icon": "cart",
        "purpose": "Build scalable product-led businesses by identifying demand, validating opportunities and using digital channels to reach customers efficiently.",
        "core": "Build scalable product and digital businesses using modern commerce channels and validated customer demand.",
        "vision": "To create accessible, scalable businesses that connect meaningful products and solutions with the people who value them.",
        "mission": "To identify promising products, ideas and digital opportunities and transform them into scalable commerce ventures through technology, partnerships and customer insight.",
        "goals": [
            "Establish selected e-commerce and drop-shipping ventures with controlled initial investment.",
            "Explore physical products, digital products and new commerce models rather than limiting the pillar to one business model.",
            "Use data and experimentation to identify scalable opportunities before committing significant capital.",
            "Build independent revenue streams that complement the HEXALIS B2B services.",
        ],
        "streams": [
            ("Dropshipping", "Supplier-fulfilled products"),
            ("D2C E-commerce", "Own online storefronts"),
            ("Marketplace Commerce", "Marketplace sales"),
            ("B2B Commerce", "Online corporate and product sales"),
            ("Curated Products", "Category and niche collections"),
            ("Private Label", "HEXALIS-owned and partner-owned brands"),
            ("Digital Products", "Templates, toolkits, resources, courses"),
            ("Subscriptions", "Recurring products and services"),
            ("New Ventures", "New validated product concepts"),
        ],
        "ladder_title": "The validation path",
        "ladder": ["Dropship", "Test", "Validate", "Stock Winners", "Private Label", "Build Brand", "Scale"],
        "ladder_note": "Drop-shipping has one job here: market validation with limited inventory commitment. It is the first rung, not the identity. Commerce is a venture-building arm, not an online store.",
        "pull": "Spend on evidence, not on optimism.",
    },
]

# --------------------------------------------------------------------------
# Enterprise-level narrative (slide 1 of the strategy document).
# --------------------------------------------------------------------------
ENTERPRISE = {
    "vision": "To build a trusted, future-ready enterprise that brings together intelligence, strategy, creativity and execution to unlock new possibilities for businesses and people.",
    "mission": "To help organizations solve challenges, accelerate growth and create sustainable value through integrated technology, strategy, brand, engagement, workplace and commerce solutions.",
    "goals": [
        ("Build trust", "Establish HEXALIS as a credible and dependable partner for businesses."),
        ("Create sustainable growth", "Develop profitable, scalable and recurring revenue across the six pillars."),
        ("Deliver measurable value", "Focus every engagement on meaningful business outcomes."),
        ("Build an integrated ecosystem", "Connect internal capabilities with a strong network of specialists, vendors and partners."),
        ("Scale with agility", "Build lean systems, technology and processes that let HEXALIS expand without unnecessary complexity."),
        ("Create long-term relationships", "Grow from individual projects into multi-service, multi-pillar strategic relationships."),
    ],
}

# --------------------------------------------------------------------------
# "One brief, six pillars" — how an integrated engagement actually looks.
# --------------------------------------------------------------------------
SCENARIOS = [
    {
        "id": "newmarket",
        "label": "A company entering a new market",
        "summary": "A business with a signed mandate for a new market, a headcount plan and eighteen months to prove it. Normally that means six procurement cycles. Here it means one.",
        "moves": [
            ("strategy", "Market-entry plan", "Operating model, entity strategy, governance and the KPI framework the board will be judged on."),
            ("technology", "The stack that runs it", "Core platforms, data and reporting, integrations with what you already run — then engineers embedded until the local team is real."),
            ("growth", "A brand that lands locally", "Positioning adapted for the market, launch campaign, creators, performance media and a lead engine that feeds the sales hire."),
            ("engagement", "The launch itself", "Announcement event, partner summit, first town hall — produced, not improvised."),
            ("workplace", "Day one for every new hire", "Joining kits, branded merchandise, office supply and a procurement rhythm that does not need a monthly escalation."),
            ("commerce", "A direct channel", "Marketplace and D2C presence tested with limited commitment before capital follows demand."),
        ],
    },
    {
        "id": "enterprise",
        "label": "An enterprise annual cycle",
        "summary": "An established Indian enterprise with a full calendar: a transformation program, a flagship conference, a rebrand and 4,000 employees to keep engaged.",
        "moves": [
            ("strategy", "Transformation, run properly", "PMO stood up, portfolio governance, process improvement and the reporting that survives a board review."),
            ("technology", "Automation where it pays", "Workflow automation, analytics and managed support on the platforms the business actually depends on."),
            ("growth", "Rebrand to market", "Brand architecture, messaging, digital presence and the always-on social and content retainer behind it."),
            ("engagement", "The flagship moments", "Annual conference, leadership town halls, employee engagement programs and sponsor management."),
            ("workplace", "Recognition that arrives on time", "Rewards, awards, delegate kits and festival gifting on a planned calendar instead of a scramble."),
            ("commerce", "New revenue, tested", "Curated product lines and B2B commerce piloted alongside the core business."),
        ],
    },
    {
        "id": "scaleup",
        "label": "A funded scale-up",
        "summary": "Series A raised, a board expecting a plan, a team of forty and no time to hire six agencies.",
        "moves": [
            ("growth", "Demand, fast", "Performance marketing, creator campaigns and a lead engine that gives the board a number to look at."),
            ("strategy", "Structure behind the sprint", "Operating model, hiring plan, KPI framework and executive advisory as the company doubles."),
            ("technology", "Engineering capacity on tap", "Staff augmentation for developers, data engineers and analysts without an eight-week hiring cycle."),
            ("commerce", "Channel expansion", "Marketplace and D2C storefronts validated before the inventory bet."),
            ("engagement", "Moments that matter", "Product launch, investor and customer events, and the internal culture programs that keep forty people together."),
            ("workplace", "Culture you can hold", "Onboarding kits and merchandise that make a fast-growing team feel like one company."),
        ],
    },
    {
        "id": "founder",
        "label": "A founder-led business",
        "summary": "A profitable, owner-run company that has outgrown its systems and wants a partner rather than a panel of consultants.",
        "moves": [
            ("strategy", "A second opinion that stays", "Growth and diversification planning, plus an ongoing advisory relationship with the founder."),
            ("technology", "Out of spreadsheets", "Process digitization, reporting and automation sized for the business, not for a Fortune 500."),
            ("growth", "A brand worthy of the business", "Identity, digital presence and a content rhythm that stops depending on the founder's own social account."),
            ("workplace", "Client and employee gifting", "Reliable, customized, on-brand and on-time."),
            ("engagement", "Customer and partner moments", "Focused events and activations that deepen the relationships already earning the revenue."),
            ("commerce", "The next line", "Digital products and curated collections that create income outside the founder's calendar."),
        ],
    },
]

# --------------------------------------------------------------------------
# How we engage.
# --------------------------------------------------------------------------
MODES = [
    ("Advisory", "Retainer",
     "Ongoing counsel for founders, CXOs and leadership teams. Standing access, a monthly rhythm, and someone who already knows the context when the question is urgent."),
    ("Project", "Fixed scope",
     "A defined outcome with a defined end. Strategy engagements, campaigns, transformation workstreams, launches, builds. Scoped, priced and delivered against a plan."),
    ("Embedded", "Talent",
     "Our specialists inside your team, on your tools, in your stand-ups. Developers, data engineers, analysts, AI specialists, project and change professionals."),
    ("Managed", "Continuous",
     "We run it. Technology support, social and content, procurement programs, commerce operations — an operating rhythm with an SLA, not a favour."),
]

PROCESS = [
    ("Diagnose", "We start with the business, not the brief. What is actually in the way, what has already been tried, and what the number needs to be."),
    ("Design", "A plan with an owner, a sequence and a cost. Pillars are chosen because they are needed, not because we sell them."),
    ("Deliver", "One team, one plan, one point of accountability — even when four pillars are moving at once."),
    ("Sustain", "The part most partners skip. Handover, capability building, managed support, and a relationship that outlasts the engagement."),
]

# Why the integrated model matters — the argument, stated plainly.
CONTRAST = {
    "fragmented": [
        "A consulting firm writes the strategy.",
        "A systems integrator builds part of it.",
        "An agency takes it to market.",
        "An events company stages the launch.",
        "A gifting vendor ships the kits, late.",
        "Someone's nephew runs the online store.",
    ],
    "integrated": [
        "One brief, understood once.",
        "One team that shares a language and a standard.",
        "Six pillars that can be switched on as needed.",
        "One commercial relationship to negotiate and renew.",
        "One escalation path when something goes wrong.",
        "A partner who is still there after the invoice clears.",
    ],
}

FAQS = [
    ("Is HEXALIS a consultancy, an agency or a supplier?",
     "All three, structured deliberately. The six pillars are separate capabilities with their own leadership, standards and economics — but a single commercial relationship and a single point of accountability. You engage the pillars you need, and the ones you do not need stay out of your way."),
    ("Do we have to buy all six?",
     "No, and most clients do not. Nearly every relationship starts inside one pillar. The point of the model is that when the second need appears — and it always does — you are not starting a procurement cycle from zero."),
    ("How do you keep quality consistent across such different work?",
     "By owning the parts that decide quality: the client relationship, the concept, the project management and the standard. Where specialist infrastructure is needed — production crews, manufacturing, fulfilment — we work through a vetted partner ecosystem, and we remain the accountable party."),
    ("What does a first conversation look like?",
     "Thirty minutes, no deck. We want to understand the business problem, what has already been tried, and what success would look like on a specific date. If HEXALIS is not the right answer, we will say so."),
    ("Where are you based and where do you work?",
     "HEXALIS is an India-based enterprise working with organizations across the country, and with international businesses building or scaling their India presence. Delivery is a mix of on-site and distributed depending on the pillar."),
]


# --------------------------------------------------------------------------
# Open positions. Source: HEXALIS_Hiring_JDs_4_Roles_V1.1.pdf (which actually
# carries seven roles). `summary` is what shows before anyone opens a role;
# everything else appears only after "Know more".
# To take a role down, delete its block. To add one, copy the shape.
# --------------------------------------------------------------------------
ROLES = [
    {
        "slug": "lead-business-operations-client-delivery",
        "title": "Lead \u2013 Business Operations and Client Delivery",
        "type": "Full-Time",
        "experience": "6\u201310 years",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "Business Operations & Delivery",
        "summary": "Own client engagements from handover to closure \u2014 keeping clients, teams, vendors and partners aligned, and commitments delivered on time.",
        "role": [
            "We are looking for a structured, dependable and client-focused Lead \u2013 Business Operations and Client Delivery who can take ownership of coordinating client engagements from business handover through execution and closure. The role will work across clients, internal teams, vendors and partners to ensure that projects are well planned, stakeholders remain aligned, risks are identified early and commitments are delivered on time and to the expected quality.",
            "This is a hands-on cross-functional role requiring strong communication, planning, project coordination, stakeholder management and operational discipline. The ideal candidate should be comfortable bringing structure to ambiguous requirements, managing multiple workstreams and acting as a dependable bridge between clients and delivery teams.",
        ],
        "responsibilities": [
            "Take ownership of assigned client engagements after handover from the Business Development team.",
            "Understand project scope, client expectations, timelines, deliverables and dependencies.",
            "Develop and maintain project plans, action trackers, schedules, milestones and status reports.",
            "Coordinate activities across HEXALIS teams, vendors, partners and external stakeholders.",
            "Act as a key operational point of contact for clients during project execution.",
            "Maintain clear and regular communication on progress, requirements, approvals, risks and pending actions.",
            "Conduct or support project review meetings and document key actions and decisions.",
            "Monitor project timelines and ensure timely follow-up across internal and external teams.",
            "Identify delivery risks, delays and dependencies and initiate appropriate corrective actions.",
            ("Coordinate cross-functional assignments across areas such as:", [
                "Brand and digital campaigns",
                "Client and stakeholder engagement initiatives",
                "Corporate events and activations",
                "Influencer and creator campaigns",
                "Corporate gifting and merchandise",
                "Procurement and product sourcing",
                "Employee engagement programmes",
                "Commerce and other business initiatives",
            ]),
            "Coordinate vendors and partners on deliverables, timelines, requirements and quality.",
            "Support internal teams in obtaining client approvals, inputs and decisions required for execution.",
            "Track project deliverables against agreed scope and highlight deviations where necessary.",
            "Maintain accurate documentation, project trackers and operational records.",
            "Support project closure, including completion tracking, feedback, pending actions and handover.",
            "Develop and improve SOPs, checklists, templates and standard operating processes.",
            "Identify opportunities to improve delivery efficiency, client experience and cross-functional coordination.",
            "Support Business Development and Client Success teams with repeat requirements, ongoing client needs and account continuity.",
            "Prepare periodic management updates on project status, risks, priorities and operational performance.",
            "Support special projects and business initiatives requiring cross-functional coordination.",
        ],
        "profile": [
            "6\u201310 years of relevant experience in Client Delivery, Project Coordination, Business Operations, Programme Management, Client Servicing, Account Operations or related roles. Bachelor\u2019s degree in Business, Management, Operations, or a related field.",
            "Strong experience managing multiple stakeholders, timelines and deliverables.",
            "Excellent verbal and written communication skills. Good problem-solving and decision-making skills.",
            "Strong attention to detail, commitment to deliver quality and ability to identify risks and dependencies proactively.",
            "Comfortable working with internal teams, vendors, partners and external stakeholders.",
            "Working knowledge of MS Office / Google Workspace, spreadsheets, presentations and project/task-management tools.",
            "Ability to prepare structured trackers, project updates, meeting notes and management reports.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model and travel locally when project requirements demand.",
        ],
        "preferred_intro": "Exposure to one or more of the following would be an advantage:",
        "preferred": ["Client Servicing", "Project & Programme Management", "Business Operations",
                      "Stakeholder Management", "Campaign Management", "Corporate Events", "Vendor Management",
                      "Digital Marketing Projects", "Procurement", "Account Management", "PMO",
                      "Process Improvement", "Training & Facilitation"],
        "note": "",
    },
    {
        "slug": "business-development-executive",
        "title": "Business Development Executive",
        "type": "Full-Time",
        "experience": "3\u20136 years",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "Business Development & Client Success",
        "summary": "Identify new opportunities, build relationships with corporate decision-makers and convert business conversations into meaningful opportunities.",
        "role": [
            "We are looking for a motivated and commercially driven Business Development Executive who can identify new opportunities, build relationships with corporate decision-makers, understand client requirements and convert business conversations into meaningful opportunities.",
            "This is not purely a lead-generation role. The person will participate across the business-development lifecycle \u2014 from prospecting and client conversations through proposals, negotiations, closure and account development. The role also involves researching market trends, preparing business proposals, maintaining accurate records, and providing regular reports on sales activities and performance.",
        ],
        "responsibilities": [
            "Identify and develop new B2B business opportunities across target industries and accounts.",
            "Research prospective companies, decision-makers and relevant business requirements.",
            "Generate leads through networking, referrals, LinkedIn, email, calls and other appropriate channels.",
            "Conduct initial client discussions to understand business needs, priorities, budgets and timelines.",
            ("Build opportunities across areas such as:", [
                "Brand & product promotion",
                "Digital and social media marketing",
                "Influencer and content marketing",
                "Corporate gifting and branded merchandise",
                "Employee kits and engagement solutions",
                "Procurement and product sourcing",
                "B2B commerce and marketplace opportunities",
                "E-commerce, D2C and private-label opportunities",
            ]),
            "Coordinate with internal teams, partners and vendors to develop solutions and proposals.",
            "Prepare and present proposals, quotations and commercial offerings.",
            "Participate in commercial discussions and negotiations.",
            "Maintain regular follow-ups and progress opportunities toward closure.",
            "Maintain an accurate sales pipeline and CRM/tracking information.",
            "Develop existing client relationships and identify repeat, cross-sell and upsell opportunities.",
            "Support smooth handover of won opportunities to delivery teams.",
        ],
        "profile": [
            "3\u20136 years of relevant experience in Business Development, B2B Sales, Client Acquisition, Account Management or Solution Sales.",
            "Bachelor\u2019s degree in Business, Marketing, Management, or a related field; relevant sales or business development experience is a must.",
            "Experience working with corporate customers and business decision-makers.",
            "Effective communication skills, including clear verbal and written communication and the ability to present to diverse stakeholders.",
            "Market research capabilities to analyze trends, competition, and customer needs in relevant geographies.",
            "Strong analytical skills, ability to understand business requirements and identify suitable solutions.",
            "Comfortable handling client meetings, presentations, proposals and commercial discussions.",
            "Working knowledge of MS Office / Google Workspace, CRM and other tools.",
            "Self-driven, organized and comfortable working in a growing entrepreneurial environment.",
            "Ability to work on-site in Gurugram, Delhi \u2013 NCR, travel locally as needed, and collaborate effectively with cross-functional teams.",
        ],
        "preferred_intro": "Exposure to one or more of the following would be an advantage:",
        "preferred": ["Digital Marketing", "Brand Promotion", "Influencer Marketing", "Corporate Gifting",
                      "Merchandise", "Events", "Procurement", "Product Sourcing", "B2B Services",
                      "E-commerce", "Marketplace Business"],
        "note": "",
    },
    {
        "slug": "business-development-intern",
        "title": "Business Development Intern / Trainee",
        "type": "Internship / Trainee",
        "experience": "0\u20131 year",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "1 open position",
        "summary": "Hands-on exposure to market research, lead generation, client outreach and proposals, working closely with the Business Development team.",
        "role": [
            "We are looking for an enthusiastic and commercially curious Business Development Intern / Trainee who is interested in building a career in B2B business development, client acquisition and solution selling.",
            "The role will provide hands-on exposure to market research, prospect identification, lead generation, client outreach, CRM management, proposal support and business-development activities across HEXALIS.",
            "The selected candidate will work closely with the Business Development team and gain practical understanding of how business opportunities are identified, developed and converted into client engagements.",
        ],
        "responsibilities": [
            "Research prospective companies, industries, markets and business opportunities.",
            "Identify relevant decision-makers across functions such as Marketing, Procurement, HR, Administration, Corporate Communications and Business Leadership. Build and maintain structured prospect and contact databases.",
            "Support lead-generation activities through LinkedIn, email, calls, networking and other appropriate channels.",
            "Assist in preparing account profiles and background research before client meetings.",
            "Support outreach campaigns and follow-up activities with prospective clients.",
            "Maintain accurate lead, opportunity and follow-up information in CRM or sales trackers.",
            "Assist the Business Development team in preparing presentations, proposals, quotations and other client-facing material.",
            "Research market trends, competitors and emerging business opportunities.",
            ("Support business-development activities across areas such as:", [
                "Brand & product promotion",
                "Digital and social media marketing",
                "Influencer and content marketing",
                "Corporate gifting and branded merchandise",
                "Employee kits and engagement solutions",
                "Procurement and product sourcing",
                "B2B commerce and marketplace opportunities",
                "E-commerce, D2C and private-label opportunities",
            ]),
            "Coordinate internally with relevant teams to collect information required for proposals and client discussions.",
            "Track follow-ups, meetings, proposals and next actions.",
            "Support preparation of periodic sales and business-development reports.",
            "Participate in client meetings and business discussions where appropriate.",
        ],
        "profile": [
            "0\u20131 year of experience; fresh graduates and candidates with relevant internship experience are welcome to apply.",
            "Bachelor\u2019s degree or pursuing final year in Business, Marketing, Management, Commerce, Economics or a related field.",
            "Strong interest in Business Development, B2B Sales, Client Acquisition or Account Management.",
            "Good verbal and written communication skills.",
            "Comfortable researching companies, industries and business decision-makers.",
            "Basic understanding of sales, marketing and business concepts.",
            "Strong internet research and analytical skills. Familiarity with LinkedIn and digital research tools.",
            "Working knowledge of MS Office / Google Workspace. Organized, detail-oriented and disciplined with follow-ups.",
            "Self-motivated with a willingness to learn and take ownership. Comfortable working in a growing entrepreneurial environment.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model and travel locally when necessary.",
        ],
        "preferred_intro": "Exposure through academic projects, internships or previous work in one or more of the following would be an advantage:",
        "preferred": ["Business Development", "B2B Sales", "Market Research", "Lead Generation",
                      "Digital Marketing", "Corporate Gifting", "Events", "Procurement",
                      "E-commerce", "Marketplace Business", "Client Relationship Management"],
        "note": "",
    },
    {
        "slug": "events-campaign-coordinator",
        "title": "Events & Campaign Coordinator",
        "type": "Full-Time",
        "experience": "2\u20135 years",
        "work_model": "Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "",
        "summary": "Plan and deliver corporate events, brand activations, engagement initiatives and integrated marketing campaigns, end to end.",
        "role": [
            "We are looking for an organized, proactive and execution-focused Events & Campaign Coordinator who can support the planning and delivery of corporate events, brand activations, engagement initiatives and integrated marketing campaigns.",
            "The role will involve coordinating clients, internal teams, vendors, partners and other stakeholders to ensure that events and campaigns are delivered smoothly, on time and within agreed requirements. The ideal candidate should be comfortable managing multiple activities simultaneously and should have strong coordination, communication and problem-solving skills.",
        ],
        "responsibilities": [
            "Support planning and execution of corporate events, conferences, product launches, brand activations and engagement initiatives.",
            "Coordinate end-to-end operational activities including timelines, vendors, logistics, materials and deliverables.",
            "Understand client requirements and translate them into clear execution plans and action trackers.",
            "Coordinate with internal teams, vendors, agencies, venues, suppliers and partners.",
            ("Support execution of:", [
                "Corporate events and conferences",
                "Product launches and brand activations",
                "Employee engagement programs",
                "Customer and partner engagement initiatives",
                "Exhibitions, trade shows, experiential marketing campaigns",
                "Influencer and creator campaigns",
                "Brand and promotional campaigns",
            ]),
            "Prepare and maintain event plans, campaign trackers, timelines, checklists and status reports.",
            "Coordinate venue identification, vendor quotations, bookings and operational requirements.",
            "Support sourcing of event merchandise, gifting, branding materials and promotional items.",
            "Coordinate creative requirements such as event branding, invitations, signage, presentations and digital content.",
            "Liaise with influencers, creators, agencies and campaign partners where required.",
            "Track deliverables, approvals and deadlines across multiple stakeholders.",
            "Support client meetings, briefings, rehearsals and event-day coordination.",
            "Monitor event and campaign execution and resolve operational issues promptly.",
            "Coordinate post-event or post-campaign activities including reporting, feedback and closure.",
            "Maintain accurate records of vendors, quotations, expenses, deliverables and project documentation.",
            "Support preparation of client proposals, presentations and campaign concepts where required.",
            "Identify opportunities to improve event execution, vendor performance and overall client experience.",
        ],
        "profile": [
            "2\u20135 years of relevant experience in Events, Campaign Management, Brand Activations, Experiential Marketing, Event Operations or a related role.",
            "Bachelor\u2019s degree in Event Management, Marketing, Mass Communication, Hospitality, Business, Media or a related field.",
            "Hands-on experience coordinating corporate events, campaigns or activations.",
            "Strong planning, coordination and organizational skills.",
            "Ability to manage multiple vendors, stakeholders and timelines simultaneously.",
            "Good verbal and written communication skills. Good negotiation and vendor-management skills.",
            "Comfortable interacting with clients, suppliers, agencies and external partners.",
            "Strong attention to detail and ability to work under tight timelines.",
            "Working knowledge of MS Office / Google Workspace and project or task-tracking tools.",
            "Ability to prepare structured trackers, checklists and status reports.",
            "Comfortable working during event-specific hours, including occasional evenings or weekends when required.",
            "Willingness to travel within Delhi NCR and to other locations for events or client requirements where necessary.",
            "Self-driven, resourceful and comfortable working in a growing entrepreneurial environment.",
        ],
        "preferred_intro": "Exposure to one or more of the following would be an advantage:",
        "preferred": ["Corporate Events", "Conferences", "Product Launches", "Brand Activations",
                      "Employee Engagement", "Experiential Marketing", "Exhibitions", "Trade Shows",
                      "Influencer Campaigns", "Vendor Management", "Event Merchandise",
                      "Corporate Gifting", "Digital Campaigns", "Client Servicing"],
        "note": "",
    },
    {
        "slug": "founders-office-intern",
        "title": "Founder\u2019s Office Intern / Trainee",
        "type": "Internship / Trainee",
        "experience": "0\u20131 year",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "1 open position",
        "summary": "Work directly with the Founder & CEO on research, strategy, planning and special projects across all six pillars.",
        "role": [
            "We are looking for a curious, structured and highly driven Founder\u2019s Office Intern / Trainee who is interested in gaining hands-on exposure to how an early-stage business is built, managed and scaled.",
            "The role will work closely with the Founder & CEO across business research, strategic initiatives, planning, project coordination, market analysis, partnerships, internal operations and special projects.",
            "This is not a traditional administrative or personal-assistant role. The position is designed for someone who wants broad exposure to entrepreneurship, business building and cross-functional execution.",
        ],
        "responsibilities": [
            "Support the Founder & CEO on strategic and business-building initiatives.",
            "Conduct research on markets, industries, competitors, business models and emerging opportunities.",
            "Prepare business summaries, research notes, presentations and decision-support material.",
            "Support evaluation of new business opportunities across HEXALIS business pillars.",
            "Assist with business planning, initiative tracking and follow-up on key priorities.",
            "Coordinate with internal teams, vendors, partners and external stakeholders on selected initiatives.",
            "Support preparation and tracking of action items arising from business meetings.",
            "Assist in developing presentations, proposals, concept notes and internal business documents.",
            "Research potential clients, partners, suppliers, platforms and market opportunities.",
            ("Support special projects across areas such as:", [
                "Business strategy and market research",
                "Growth and brand initiatives",
                "Corporate gifting and procurement",
                "Events and engagement",
                "Commerce and new ventures",
                "Technology and digital opportunities",
            ]),
            "Support tracking of key business metrics, priorities and management information.",
            "Assist in improving internal processes, trackers and operating systems.",
            "Coordinate information across different HEXALIS functions for Founder-level reviews.",
            "Participate in relevant client, partner and internal meetings and document key outcomes.",
            "Support other high-priority initiatives assigned by the Founder\u2019s Office.",
        ],
        "profile": [
            "0\u20131 year of experience; fresh graduates and candidates with relevant internship experience are welcome to apply.",
            "Bachelor\u2019s degree or pursuing final year in Business, Management, Commerce, Economics, Technology, Engineering or a related discipline.",
            "Strong interest in entrepreneurship, business strategy, consulting, startups or business operations.",
            "Strong research and analytical capabilities.",
            "Good verbal and written communication skills.",
            "Ability to structure information clearly and prepare concise summaries.",
            "Comfortable working with presentations, spreadsheets and business documents.",
            "Working knowledge of MS Office / Google Workspace.",
            "Strong attention to detail and ability to manage multiple priorities.",
            "Self-driven, proactive and comfortable working with limited supervision.",
            "High degree of professionalism, discretion and reliability.",
            "Ability to learn quickly and work across different business areas.",
            "Comfortable working in a fast-moving and evolving entrepreneurial environment.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model.",
        ],
        "preferred_intro": "Exposure through academic projects, internships, student organizations or previous work in one or more of the following would be an advantage:",
        "preferred": ["Business Strategy", "Management Consulting", "Market Research", "Business Analysis",
                      "Project Management", "Entrepreneurship", "Startup Operations", "Business Development",
                      "Data Analysis", "Digital Marketing", "Corporate Strategy"],
        "note": "",
    },
    {
        "slug": "digital-marketing-social-media-executive",
        "title": "Digital Marketing & Social Media Executive",
        "type": "Full-Time",
        "experience": "2\u20135 years",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "",
        "summary": "Build digital presence, audience engagement and campaign performance for HEXALIS and our clients.",
        "role": [
            "We are looking for a creative, data-aware and execution-focused Digital Marketing & Social Media Executive who can help build strong digital presence, audience engagement and campaign performance for HEXALIS and our clients.",
            "The role will involve planning and managing social media channels, developing content calendars, coordinating creatives, supporting digital campaigns, tracking performance and identifying opportunities to improve brand visibility and engagement. The ideal candidate should be comfortable combining content, social media, campaign execution and analytics in a fast-moving entrepreneurial environment.",
        ],
        "responsibilities": [
            "Plan and manage social media activities across platforms such as LinkedIn, Instagram, Facebook and other relevant channels.",
            "Develop monthly and campaign-based social media content calendars. Monitor comments, messages, audience interactions and community engagement. Coordinate with creative designers, video editors, content creators and other internal or external resources.",
            "Create content briefs, post copy, captions and campaign messaging. Schedule and publish content across relevant digital platforms.",
            "Support brand and product promotion campaigns across digital channels.",
            ("Execute and coordinate:", [
                "Social media and brand awareness campaigns",
                "Product and service promotions",
                "Content marketing initiatives",
                "Influencer and creator campaigns",
                "Lead-generation campaigns",
                "Event and activation promotions",
            ]),
            "Research digital trends, competitor activity, audience behavior and relevant content opportunities.",
            "Identify suitable hashtags, keywords, content themes and campaign ideas. Support influencer discovery, outreach, campaign coordination and performance tracking. Track campaign and social media performance using relevant platform analytics.",
            "Work with internal teams to develop content aligned with business objectives and client requirements.",
            "Prepare regular reports covering reach, engagement, follower growth, traffic, campaign performance and other relevant metrics.",
            "Use performance insights to recommend improvements in content, timing, formats and campaigns.",
            "Support basic paid digital marketing activities and coordinate with internal or external specialists where required.",
            "Maintain content, campaign and publishing trackers. Ensure all digital communication follows HEXALIS and client brand guidelines.",
            "Stay updated on social media trends, platform changes and emerging digital marketing tools.",
            "Use appropriate AI-enabled tools for research, content ideation, optimization and productivity.",
        ],
        "profile": [
            "2\u20135 years of relevant experience in Digital Marketing, Social Media Marketing, Content Marketing or a related role.",
            "Bachelor\u2019s degree in Marketing, Business, Mass Communication, Media, Advertising or a related field.",
            "Hands-on experience managing business or brand social media accounts. Good understanding of platforms such as LinkedIn, Instagram and Facebook. Experience creating and managing social media calendars and digital campaigns.",
            "Strong written communication and copywriting skills. Ability to work effectively with designers, video editors and content teams.",
            "Good understanding of social media content formats including posts, carousels, stories, reels and short-form video.",
            "Working knowledge of social media analytics and reporting.",
            "Understanding of digital marketing fundamentals including audience targeting, engagement, reach, traffic and lead generation.",
            "Familiarity with tools such as Meta Business Suite, LinkedIn Page tools, Google Analytics, Canva, scheduling platforms or similar tools.",
            "Basic understanding of paid social media advertising would be an advantage.",
            "Strong research, coordination and organizational skills. Ability to manage multiple assignments and deadlines.",
            "Self-driven, proactive and comfortable working in a growing entrepreneurial environment.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model.",
        ],
        "preferred_intro": "Exposure to one or more of the following would be an advantage:",
        "preferred": ["Brand Marketing", "Content Marketing", "Social Media Management", "Influencer Marketing",
                      "Digital Campaigns", "Lead Generation", "Paid Social Media", "Marketing Analytics",
                      "Reels & Video Content", "Event Promotion", "B2B Marketing", "AI Marketing Tools"],
        "note": "",
    },
    {
        "slug": "creative-designer-video-editor",
        "title": "Creative Designer / Video Editor",
        "type": "Full-Time",
        "experience": "2\u20135 years",
        "work_model": "Onsite/Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "",
        "summary": "Turn ideas, briefs and business messages into compelling visual content \u2014 across both static design and video.",
        "role": [
            "We are looking for a creative, versatile and execution-focused Creative Designer / Video Editor who can translate ideas, briefs and business messages into compelling visual content. The role will support both HEXALIS brand communication and client assignments, covering social media creatives, digital campaigns, videos, reels, presentations, product mock-ups, event creatives and other marketing collateral.",
            "The ideal candidate should be equally comfortable with static design and video content, have a strong visual sense, and be able to take ownership of creative assignments from concept through final delivery.",
        ],
        "responsibilities": [
            "Design high-quality visual content for all social media platforms including LinkedIn, Instagram, YouTube, Facebook, etc.",
            "Create social media posts, carousels, stories, banners, campaign creatives and digital advertisements.",
            "Edit reels, short-form videos, promotional videos, event videos and other digital content.",
            "Develop engaging motion graphics, animated text, transitions and visual effects where required.",
            "Translate campaign briefs, concepts and business messages into strong creative ideas and visual narratives.",
            ("Create visual assets for:", [
                "Brand and product promotion",
                "Digital and social media campaigns",
                "Corporate events and brand activations",
                "Corporate gifting and branded merchandise",
                "Product launches and promotions",
                "Client presentations, proposals and internal & external HEXALIS communications",
            ]),
            "Design professional presentations, brochures, flyers, one-pagers and other marketing collateral.",
            "Create and enhance product mock-ups, packaging concepts and presentation visuals.",
            "Edit and enhance images, photographs and product visuals as required.",
            "Support content shoots, product photography and video production activities where needed.",
            "Work with marketing, content, campaign and business teams to understand creative requirements.",
            "Ensure consistency with HEXALIS and client brand guidelines, including typography, colors, imagery and visual identity.",
            "Manage multiple creative assignments while maintaining quality and agreed timelines. Incorporate feedback and revisions efficiently.",
            "Stay updated on design trends, social media formats, video styles and emerging creative technologies.",
            "Use appropriate AI-enabled creative tools to improve ideation, productivity and quality while maintaining brand consistency.",
        ],
        "profile": [
            "2\u20135 years of relevant experience in Graphic Design, Creative Design, Video Editing, Digital Content or a related creative role.",
            "Bachelor\u2019s degree / Diploma in Graphic Design, Visual Communication, Multimedia, Animation, Fine Arts, Media or a related field.",
            "Strong portfolio demonstrating both graphic design and video-editing capabilities.",
            "Strong understanding of typography, composition, color, visual hierarchy and brand consistency.",
            "Proficiency in tools such as Adobe Photoshop, Illustrator, Premiere Pro and After Effects, or equivalent professional design and video-editing platforms. Experience with tools such as Canva, Figma, CapCut or DaVinci Resolve would be an advantage.",
            "Strong understanding of social media content formats, particularly LinkedIn, Instagram, reels and short-form video.",
            "Ability to independently interpret a creative brief and develop polished output with limited supervision.",
            "Good understanding of video storytelling, pacing, music, transitions, captions and platform-specific content.",
            "Strong attention to detail with an ability to maintain visual consistency across multiple assets.",
            "Ability to manage multiple projects, priorities and deadlines. Comfortable receiving feedback and making revisions quickly.",
            "Good communication and collaboration skills. Self-driven, creative and comfortable working in a growing entrepreneurial environment.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model.",
        ],
        "preferred_intro": "Exposure to one or more of the following would be an advantage:",
        "preferred": ["Social Media Design", "Video Editing", "Reels & Short-Form Content", "Motion Graphics",
                      "Brand Design", "Digital Campaigns", "Presentation Design", "Product Mock-ups",
                      "Event Creatives", "Packaging Design", "Photography", "AI Creative Tools"],
        "note": "A portfolio / showreel demonstrating relevant design and video work will be required as part of the application process.",
    },
    {
        "slug": "creative-design-video-intern",
        "title": "Creative Design & Video Content Intern / Trainee",
        "type": "Internship / Trainee",
        "experience": "0\u20131 year",
        "work_model": "Hybrid",
        "location": "Gurugram, Haryana",
        "extra": "3\u20136 month internship",
        "summary": "Create visual content for live brands and campaigns alongside the Growth & Brand Solutions team.",
        "role": [
            "We are looking for a creative and detail-oriented Creative Design & Video Content Intern / Trainee who is passionate about visual communication, digital content and brand storytelling.",
            "The role will support the creation of visual content for HEXALIS and client projects, including social media creatives, reels, videos, campaign assets, presentations, brochures, product mock-ups and other digital marketing collateral.",
            "The selected candidate will work closely with the Growth & Brand Solutions team and gain hands-on exposure to live brands, campaigns and client assignments across different industries.",
        ],
        "responsibilities": [
            "Create engaging visual content for LinkedIn, Instagram and other digital platforms.",
            "Design social media posts, stories, carousels, banners and campaign creatives.",
            "Edit short-form videos, reels and promotional content for digital and social media platforms.",
            "Support creation of basic motion graphics, animated text, transitions and visual effects.",
            "Translate creative briefs, concepts and content ideas into effective visual communication.",
            ("Develop visual assets for:", [
                "Brand and product promotion",
                "Digital and social media campaigns",
                "Influencer and creator campaigns",
                "Corporate events and activations",
                "Corporate gifting and merchandise",
                "Product presentations and mock-ups",
                "Client proposals and presentations",
            ]),
            "Create and edit presentation decks, brochures, flyers and other marketing collateral.",
            "Resize and adapt creatives for different platforms, formats and dimensions.",
            "Support product-image editing, enhancement and presentation mock-ups where required.",
            "Assist with video shoots, content production and basic photography when required.",
            "Organize design files, raw footage, templates and creative assets systematically.",
            "Incorporate feedback and revisions within agreed timelines.",
            "Collaborate with marketing, content, campaign and business teams on creative requirements.",
            "Stay updated on design, video, social media and digital-content trends.",
        ],
        "profile": [
            "0\u20131 year of experience; fresh graduates and candidates with relevant internship or freelance experience are welcome to apply.",
            "Pursuing or completed a Bachelor\u2019s degree / Diploma in Graphic Design, Visual Communication, Multimedia, Animation, Mass Communication, Media, Fine Arts or a related field.",
            "Good understanding of design principles, typography, composition, color and visual hierarchy.",
            "Working knowledge of one or more design tools such as Adobe Photoshop, Illustrator, Canva, Figma or similar platforms.",
            "Working knowledge of video-editing tools such as Adobe Premiere Pro, After Effects, CapCut, DaVinci Resolve or similar platforms.",
            "Basic understanding of video storytelling, pacing, transitions, music, captions and social-media formats.",
            "Good attention to detail and visual consistency. Open to feedback and able to iterate quickly.",
            "Comfortable working on multiple assignments and meeting deadlines.",
            "Self-driven, curious and willing to experiment with new creative approaches and tools.",
            "Ability to work on-site in Gurugram / Delhi NCR as required under the hybrid model.",
        ],
        "preferred_intro": "Exposure through academic projects, internships, freelance assignments or personal projects in one or more of the following would be an advantage:",
        "preferred": ["Graphic Design", "Social Media Creatives", "Video Editing", "Reels & Short-Form Content",
                      "Motion Graphics", "Brand Design", "Digital Marketing", "Presentation Design",
                      "Product Mock-ups", "Photography", "AI Creative Tools"],
        "note": "A portfolio, showreel or samples of previous design/video work will be required as part of the application.",
    },
]
